version: "3.9"
services:
  app:
    build: .
    ports:
      - "10101:10101"
    volumes:
      - ./db:/var/lib/postgresql/data
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/docker
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: docker

  db:
    image: postgres:14
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    restart: always